import { builtinModules } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { defineConfig } from "vite";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
];

function syncMainJsPlugin() {
	const buildDir = resolve(".vite-build");
	const buildMainJs = resolve(buildDir, "main.js");
	const rootMainJs = resolve("main.js");

	return {
		name: "sync-main-js",
		async closeBundle() {
			const bundle = await readFile(buildMainJs, "utf8");
			await mkdir(dirname(rootMainJs), { recursive: true });
			await writeFile(rootMainJs, bundle);
		},
	};
}

export default defineConfig(({ mode }) => ({
	plugins: [syncMainJsPlugin()],
	build: {
		emptyOutDir: true,
		lib: {
			entry: "src/main.ts",
			formats: ["cjs"],
			fileName: () => "main.js",
		},
		minify: mode === "production",
		outDir: ".vite-build",
		rollupOptions: {
			external,
			output: {
				banner,
				exports: "default",
			},
		},
		sourcemap: mode === "production" ? false : "inline",
		target: "es2020",
	},
}));
